# Generated by Django 2.2.10 on 2020-05-22 02:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ad', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='venue',
            name='detail_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad.Detail', verbose_name='Detail'),
        ),
        migrations.AddField(
            model_name='images',
            name='detail_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad.Detail', verbose_name='Detail'),
        ),
        migrations.AddField(
            model_name='dish_menu',
            name='venue_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad.Venue', verbose_name='Venue'),
        ),
        migrations.AddField(
            model_name='detail',
            name='loction_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad.Location', verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='contact',
            name='detail_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad.Detail', verbose_name='Detail'),
        ),
    ]
