# Generated by Django 2.2.10 on 2020-05-22 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0002_auto_20200522_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Deactive', 'Deactive'), ('Expire', 'Expire')], default='Pending', max_length=50),
        ),
    ]
