# Generated by Django 3.0.8 on 2020-07-26 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0005_auto_20200522_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='bridal_makeup',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
