# Generated by Django 3.0.8 on 2020-07-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0006_venue_bridal_makeup'),
    ]

    operations = [
        migrations.AddField(
            model_name='venueprice',
            name='air_conditioner_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='venueprice',
            name='bridal_makeup_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='venueprice',
            name='generator_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='venueprice',
            name='outside_catering_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='venueprice',
            name='outside_decoration_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='venueprice',
            name='outside_dj_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='venueprice',
            name='valet_parking_price',
            field=models.IntegerField(default=0),
        ),
    ]
