# Generated by Django 3.0.8 on 2020-07-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0007_auto_20200726_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venueprice',
            name='BridalRoom',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venueprice',
            name='air_conditioner_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venueprice',
            name='bridal_makeup_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venueprice',
            name='decoration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venueprice',
            name='dj_system',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venueprice',
            name='generator_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venueprice',
            name='heater',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venueprice',
            name='outside_catering_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venueprice',
            name='outside_decoration_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venueprice',
            name='outside_dj_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venueprice',
            name='per_guest',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venueprice',
            name='valet_parking_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venueprice',
            name='wiFi',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
