# Generated by Django 3.0.8 on 2020-07-31 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0008_auto_20200726_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venueprice',
            old_name='BridalRoom',
            new_name='air_conditioner',
        ),
        migrations.RenameField(
            model_name='venueprice',
            old_name='air_conditioner_price',
            new_name='bridal_makeup',
        ),
        migrations.RenameField(
            model_name='venueprice',
            old_name='bridal_makeup_price',
            new_name='bridal_room',
        ),
        migrations.RenameField(
            model_name='venueprice',
            old_name='generator_price',
            new_name='generator',
        ),
        migrations.RenameField(
            model_name='venueprice',
            old_name='outside_catering_price',
            new_name='outside_catering',
        ),
        migrations.RenameField(
            model_name='venueprice',
            old_name='outside_decoration_price',
            new_name='outside_decoration',
        ),
        migrations.RenameField(
            model_name='venueprice',
            old_name='outside_dj_price',
            new_name='outside_dj',
        ),
        migrations.RenameField(
            model_name='venueprice',
            old_name='valet_parking_price',
            new_name='valet_parking',
        ),
        migrations.RenameField(
            model_name='venueprice',
            old_name='wiFi',
            new_name='wifi',
        ),
        migrations.AlterField(
            model_name='detail',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Deactive', 'Deactive'), ('Expire', 'Expire')], default='Active', max_length=50),
        ),
    ]
